name: Sync LeetCode

on:
  schedule:
    - cron: "0 22 * * 0-4,6"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-username: YOUR_USERNAME
